// SmartSearch — Semantic Boundary Chunker
// Splits documents into coherent chunks based on topic transitions,
// not arbitrary token limits.

use unicode_segmentation::UnicodeSegmentation;
use log::debug;

/// Configuration for the semantic chunker
#[derive(Debug, Clone)]
pub struct ChunkerConfig {
    /// Maximum tokens per chunk (fallback split if exceeded)
    pub max_chunk_tokens: usize,
    /// Minimum tokens per chunk (merge with adjacent if below)
    pub min_chunk_tokens: usize,
    /// Percentile threshold for boundary detection (0.0 - 1.0)
    /// Higher = more aggressive splitting
    pub boundary_percentile: f64,
    /// Approximate tokens-per-word ratio for rough estimation
    pub tokens_per_word: f64,
}

impl Default for ChunkerConfig {
    fn default() -> Self {
        Self {
            max_chunk_tokens: 1500,
            min_chunk_tokens: 50,
            boundary_percentile: 0.90,
            tokens_per_word: 1.3,
        }
    }
}

/// A text chunk with metadata
#[derive(Debug, Clone, serde::Serialize)]
pub struct TextChunk {
    pub content: String,
    pub chunk_index: usize,
    pub start_line: usize,
    pub end_line: usize,
    pub estimated_tokens: usize,
}

/// Segment text into sentences using Unicode-aware segmentation
pub fn segment_sentences(text: &str) -> Vec<SentenceSpan> {
    let mut sentences = Vec::new();
    let mut current_line = 1;
    let mut pos = 0;

    // Use unicode_segmentation for sentence boundaries
    for sentence in text.split_sentence_bounds() {
        let trimmed = sentence.trim();
        if trimmed.is_empty() {
            // Count newlines in whitespace
            current_line += sentence.matches('\n').count();
            pos += sentence.len();
            continue;
        }

        let start_line = current_line;
        current_line += sentence.matches('\n').count();
        let end_line = current_line;

        sentences.push(SentenceSpan {
            text: trimmed.to_string(),
            start_line,
            end_line,
            start_offset: pos,
            end_offset: pos + sentence.len(),
        });

        pos += sentence.len();
    }

    sentences
}

/// Perform semantic chunking using embedding-based boundary detection
///
/// The `embeddings` parameter contains one embedding vector per sentence,
/// generated by the AI provider in a batch call.
pub fn semantic_chunk(
    sentences: &[SentenceSpan],
    embeddings: &[Vec<f32>],
    config: &ChunkerConfig,
) -> Vec<TextChunk> {
    if sentences.is_empty() {
        return vec![];
    }

    if sentences.len() == 1 {
        return vec![TextChunk {
            content: sentences[0].text.clone(),
            chunk_index: 0,
            start_line: sentences[0].start_line,
            end_line: sentences[0].end_line,
            estimated_tokens: estimate_tokens(&sentences[0].text, config.tokens_per_word),
        }];
    }

    // Step 1: Calculate cosine similarity between adjacent sentences
    let mut similarities: Vec<f64> = Vec::with_capacity(sentences.len() - 1);
    for i in 0..embeddings.len() - 1 {
        let sim = cosine_similarity(&embeddings[i], &embeddings[i + 1]);
        similarities.push(sim);
    }

    debug!("Cosine similarities between adjacent sentences: {:?}", similarities);

    // Step 2: Find boundary points using percentile threshold
    let boundaries = detect_boundaries(&similarities, config.boundary_percentile);

    debug!("Detected boundaries at sentence indices: {:?}", boundaries);

    // Step 3: Form chunks from boundary points
    let mut chunks = Vec::new();
    let mut chunk_start = 0;

    for &boundary in &boundaries {
        let chunk = form_chunk(sentences, chunk_start, boundary, chunks.len(), config);
        chunks.push(chunk);
        chunk_start = boundary + 1;
    }

    // Add final chunk
    if chunk_start < sentences.len() {
        let chunk = form_chunk(sentences, chunk_start, sentences.len() - 1, chunks.len(), config);
        chunks.push(chunk);
    }

    // Step 4: Post-process — merge tiny chunks, split oversized ones
    post_process_chunks(chunks, config)
}

/// Fallback chunking: fixed-size with overlap (used when no embeddings available)
pub fn fixed_size_chunk(text: &str, config: &ChunkerConfig) -> Vec<TextChunk> {
    let sentences = segment_sentences(text);
    if sentences.is_empty() {
        return vec![];
    }

    let mut chunks = Vec::new();
    let mut current_chunk_sentences: Vec<&SentenceSpan> = Vec::new();
    let mut current_tokens = 0;

    for sentence in &sentences {
        let sentence_tokens = estimate_tokens(&sentence.text, config.tokens_per_word);

        if current_tokens + sentence_tokens > config.max_chunk_tokens && !current_chunk_sentences.is_empty() {
            // Emit current chunk
            let content: String = current_chunk_sentences
                .iter()
                .map(|s| s.text.as_str())
                .collect::<Vec<_>>()
                .join(" ");

            chunks.push(TextChunk {
                content,
                chunk_index: chunks.len(),
                start_line: current_chunk_sentences.first().unwrap().start_line,
                end_line: current_chunk_sentences.last().unwrap().end_line,
                estimated_tokens: current_tokens,
            });

            current_chunk_sentences.clear();
            current_tokens = 0;
        }

        current_chunk_sentences.push(sentence);
        current_tokens += sentence_tokens;
    }

    // Emit remaining
    if !current_chunk_sentences.is_empty() {
        let content: String = current_chunk_sentences
            .iter()
            .map(|s| s.text.as_str())
            .collect::<Vec<_>>()
            .join(" ");

        chunks.push(TextChunk {
            content,
            chunk_index: chunks.len(),
            start_line: current_chunk_sentences.first().unwrap().start_line,
            end_line: current_chunk_sentences.last().unwrap().end_line,
            estimated_tokens: current_tokens,
        });
    }

    chunks
}

// ═══════════════════════════════════════════════════════════════════════
// Internal helpers
// ═══════════════════════════════════════════════════════════════════════

#[derive(Debug, Clone)]
pub struct SentenceSpan {
    pub text: String,
    pub start_line: usize,
    pub end_line: usize,
    pub start_offset: usize,
    pub end_offset: usize,
}

/// Compute cosine similarity between two vectors
fn cosine_similarity(a: &[f32], b: &[f32]) -> f64 {
    let dot: f64 = a.iter().zip(b.iter()).map(|(x, y)| (*x as f64) * (*y as f64)).sum();
    let norm_a: f64 = a.iter().map(|x| (*x as f64) * (*x as f64)).sum::<f64>().sqrt();
    let norm_b: f64 = b.iter().map(|x| (*x as f64) * (*x as f64)).sum::<f64>().sqrt();

    if norm_a == 0.0 || norm_b == 0.0 {
        return 0.0;
    }

    dot / (norm_a * norm_b)
}

/// Find indices where the similarity drops below the percentile threshold
fn detect_boundaries(similarities: &[f64], percentile: f64) -> Vec<usize> {
    if similarities.is_empty() {
        return vec![];
    }

    // Calculate distances (1 - similarity)
    let distances: Vec<f64> = similarities.iter().map(|s| 1.0 - s).collect();

    // Find the percentile threshold
    let mut sorted = distances.clone();
    sorted.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));

    let percentile_idx = ((percentile * sorted.len() as f64) as usize).min(sorted.len() - 1);
    let threshold = sorted[percentile_idx];

    debug!("Boundary threshold ({}th percentile): {:.4}", (percentile * 100.0) as usize, threshold);

    // Find boundaries where distance exceeds threshold
    distances
        .iter()
        .enumerate()
        .filter(|(_, &d)| d >= threshold && d > 0.1) // Also require minimum absolute distance
        .map(|(i, _)| i)
        .collect()
}

/// Form a chunk from a range of sentences
fn form_chunk(
    sentences: &[SentenceSpan],
    start: usize,
    end: usize,
    chunk_index: usize,
    config: &ChunkerConfig,
) -> TextChunk {
    let content: String = sentences[start..=end]
        .iter()
        .map(|s| s.text.as_str())
        .collect::<Vec<_>>()
        .join(" ");

    TextChunk {
        content: content.clone(),
        chunk_index,
        start_line: sentences[start].start_line,
        end_line: sentences[end].end_line,
        estimated_tokens: estimate_tokens(&content, config.tokens_per_word),
    }
}

/// Post-process chunks: merge tiny chunks, split oversized ones
fn post_process_chunks(mut chunks: Vec<TextChunk>, config: &ChunkerConfig) -> Vec<TextChunk> {
    // Merge chunks that are too small
    let mut merged: Vec<TextChunk> = Vec::new();

    for chunk in chunks.drain(..) {
        if let Some(last) = merged.last_mut() {
            if last.estimated_tokens < config.min_chunk_tokens
                || chunk.estimated_tokens < config.min_chunk_tokens
            {
                // Merge with previous
                last.content = format!("{} {}", last.content, chunk.content);
                last.end_line = chunk.end_line;
                last.estimated_tokens = estimate_tokens(&last.content, config.tokens_per_word);
                continue;
            }
        }
        merged.push(chunk);
    }

    // Re-index chunks
    for (i, chunk) in merged.iter_mut().enumerate() {
        chunk.chunk_index = i;
    }

    // Split chunks that are too large (fallback: split at midpoint)
    let mut final_chunks: Vec<TextChunk> = Vec::new();
    for chunk in merged {
        if chunk.estimated_tokens > config.max_chunk_tokens {
            // Split at sentence boundaries
            let sub_sentences = segment_sentences(&chunk.content);
            let mid = sub_sentences.len() / 2;

            if mid > 0 && sub_sentences.len() > 1 {
                let first_half: String = sub_sentences[..mid]
                    .iter()
                    .map(|s| s.text.as_str())
                    .collect::<Vec<_>>()
                    .join(" ");
                let second_half: String = sub_sentences[mid..]
                    .iter()
                    .map(|s| s.text.as_str())
                    .collect::<Vec<_>>()
                    .join(" ");

                final_chunks.push(TextChunk {
                    content: first_half.clone(),
                    chunk_index: final_chunks.len(),
                    start_line: chunk.start_line,
                    end_line: sub_sentences[mid - 1].end_line + chunk.start_line - 1,
                    estimated_tokens: estimate_tokens(&first_half, config.tokens_per_word),
                });
                final_chunks.push(TextChunk {
                    content: second_half.clone(),
                    chunk_index: final_chunks.len(),
                    start_line: sub_sentences[mid].start_line + chunk.start_line - 1,
                    end_line: chunk.end_line,
                    estimated_tokens: estimate_tokens(&second_half, config.tokens_per_word),
                });
            } else {
                final_chunks.push(TextChunk {
                    chunk_index: final_chunks.len(),
                    ..chunk
                });
            }
        } else {
            final_chunks.push(TextChunk {
                chunk_index: final_chunks.len(),
                ..chunk
            });
        }
    }

    final_chunks
}

/// Rough token count estimation (word count × tokens-per-word ratio)
fn estimate_tokens(text: &str, tokens_per_word: f64) -> usize {
    let word_count = text.split_whitespace().count();
    (word_count as f64 * tokens_per_word) as usize
}

// ═══════════════════════════════════════════════════════════════════════
// Extract title from document content
// ═══════════════════════════════════════════════════════════════════════

/// Extract a title from markdown content (first # heading)
pub fn extract_title(content: &str) -> Option<String> {
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("# ") {
            return Some(trimmed.trim_start_matches("# ").to_string());
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sentence_segmentation() {
        let text = "Hello world. This is a test. Another sentence here.";
        let sentences = segment_sentences(text);
        assert!(sentences.len() >= 3);
    }

    #[test]
    fn test_cosine_similarity_identical() {
        let a = vec![1.0, 0.0, 0.0];
        let b = vec![1.0, 0.0, 0.0];
        let sim = cosine_similarity(&a, &b);
        assert!((sim - 1.0).abs() < 1e-6);
    }

    #[test]
    fn test_cosine_similarity_orthogonal() {
        let a = vec![1.0, 0.0, 0.0];
        let b = vec![0.0, 1.0, 0.0];
        let sim = cosine_similarity(&a, &b);
        assert!(sim.abs() < 1e-6);
    }

    #[test]
    fn test_fixed_size_chunk() {
        let text = "First sentence. Second sentence. Third sentence. Fourth sentence. Fifth sentence.";
        let config = ChunkerConfig {
            max_chunk_tokens: 10,
            min_chunk_tokens: 2,
            ..Default::default()
        };
        let chunks = fixed_size_chunk(text, &config);
        assert!(!chunks.is_empty());
        // All text should be covered
        let reconstructed: String = chunks.iter().map(|c| c.content.as_str()).collect::<Vec<_>>().join(" ");
        assert!(reconstructed.contains("First") && reconstructed.contains("Fifth"));
    }

    #[test]
    fn test_extract_title() {
        let content = "Some preamble\n# My Document Title\n\nBody text here.";
        assert_eq!(extract_title(content), Some("My Document Title".to_string()));
    }

    #[test]
    fn test_extract_title_first_line() {
        let content = "# Quick Start Guide\n\nThis is the body.";
        assert_eq!(extract_title(content), Some("Quick Start Guide".to_string()));
    }
}
